[project]
name = "pdoc-md"
version = "0.1.0"
description = "Generate simple markdown API documentation using pdoc."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pdoc>=15.0.4",
]
